# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

variables:
- name: resouceGroup_var
  value: 'TestRGIND' 
- name: subscriptionID_var
  value: '68ef03fa-8f28-44b6-a1dd-13113c3eb580'
- name: keyVault_name
  value: 'test1111'
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARM Template'
    subscriptionId: ${{ variables.subscriptionID_var }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ variables.resouceGroup_var }}
    location: 'South India'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/sudipto92/azure-quickstart-templates/master/201-key-vault-secret-create/azuredeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/sudipto92/azure-quickstart-templates/master/201-key-vault-secret-create/parameters.json'
    deploymentMode: 'Incremental'

