trigger:
- none

pool:
  name: Default

variables:
- name: resouceGroup_var
  value: 'Devops_init' 
- name: subscriptionID_var
  value: '68ef03fa-8f28-44b6-a1dd-13113c3eb580'
- name: keyVault_name
  value: 'test1111'
steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'ARM Template'
    subscriptionId: '68ef03fa-8f28-44b6-a1dd-13113c3eb580'
    location: 'South India'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/sudipto92/azure-quickstart-templates/master/201-key-vault-secret-create/commondeploy.json'
    csmParametersFileLink: 'https://raw.githubusercontent.com/sudipto92/azure-quickstart-templates/master/201-key-vault-secret-create/parameters.json'
    overrideParameters: '-storageName test3322storage12345 -location eastus -acrName acrdemo5645 -keyvault_name testing5555 -keyName keyVaultK -_artifactsLocation https://raw.githubusercontent.com/sudipto92/azure-quickstart-templates/master/201-key-vault-secret-create/'
    deploymentMode: 'Incremental'
  displayName: 'Running ARM Template'
    
